---
- name: Install HTTPD if not installed
  ansible.builtin.package:
    name: httpd
    state: present

- name: Enable and start httpd service
  ansible.builtin.systemd:
    name: httpd
    enabled: true
    state: started
