name: TFSec Scan

on:
  push:
    branches:
      - terraform-ec2
      - staging
      - prod

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
